# Site settings
title: kristian ernst's notes
email: kristian.ernst@yahoo.com
description: "simple page containing my notes"
baseurl: ""
url: "http://kristianernst.github.io"
twitter_username: _kristianernst
github_username:  kristianernst

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
